title: 'This Workplace Learning website is supported by SkillsFuture Singapore'
title-abbreviated: 'us for any feedback on the website'
description: Description
url: 'https://www.workplacelearning.gov.sg/'
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
    - jekyll-feed
    - jekyll-assets
    - jekyll-paginate
    - jekyll-sitemap
paginate: 12
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
exclude:
    - travis-script.js
    - .travis.yml
    - README.md
    - package.json
    - package-lock.json
    - node_modules
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
collections:
    workplace-learning:
        output: true
    framework:
        output: true
    self-assessment:
        output: false
    implementations:
        output: false
    resources:
        output: true
resources_name: resources
favicon: /images/framework-icon.ico
google_analytics: null
permalink: none
baseurl: ""
defaults:
    - scope:
          path: ""
      values:
          layout: page
